-- 코드를 입력하세요
SELECT FLAVOR
  FROM 
(
SELECT (F.TOTAL_ORDER + J.TOTAL_ORDER) AS CALC_ORDER, F.FLAVOR
  FROM FIRST_HALF F
     , (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
          FROM JULY
         GROUP BY FLAVOR
        ) J
  WHERE F.FLAVOR = J.FLAVOR
 ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
)
WHERE ROWNUM <= 3;
